name: CI
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:     
  build-site:
    runs-on: ubuntu-latest
    steps:
    - name: Copy Repository Contents
      uses: actions/checkout@v2
    - name: Get recostep data
      env:
        NOTION_RECOSTEP: ${{ secrets.NOTION_RECOSTEP }}
      run: |
        echo "$NOTION_RECOSTEP"
        wget -O ./_markdowns/raw/data.zip "$NOTION_RECOSTEP"
        ls -l ./_markdowns
